### ISSUE TITLE
Varying speed between save points

### ISSUE THREAD

**Issue by RaphaelArctic** [Er1807/CameraAnimation#3]
When trying to save points for a circle, pointing inwards, the loop looks fine, but as the camera flies through them, it seems to speed up or slow down during some tracks?
Would it be possible to toggle a set speed for the entire track?

**Comment by Er1807** [comment]
It currently uses a constant time per point. But maybe I can make an option for constant speed too

**Comment by RaphaelArctic** [comment]
That would be lovely!
Another question:
I don't know how all this magic works but would it be possible to add a 2-Axis Puppet to manually move the camera along the track?
