### ISSUE TITLE
Radial wheel goes blank

### ISSUE THREAD

**Issue by jrob007** [Er1807/CameraAnimation#4]
Your camera mod is fantastic and I've used it for some recording. Just two issues I've noticed though:

The menu options from the Camera Animations radial wheel goes blank randomly. I will set a position, save/load a preset, clear it, etc. But then for whatever reason occasionally I will open the menu and it will be blank with the only option to go back. I can't seem to fix it immediately unless I restart VRChat, however what's strange is that it has also occasionally fixed itself too. I have no idea why it randomly stops working and sometimes randomly works again.

The other minor issue is with the Camera Animations option on the VRChat camera itself, selecting it overlaps other camera menu options.

**Comment by Er1807** [comment]
The redialö menu going blank should have been fixed in the latest version. was approved around 2 days in vrcmg.

for the second issue I currently have no real way of solving it. It happens if while the animation submenu is open you select another one. If you deselect it first it works fine

**Comment by jrob007** [comment]
> The redialö menu going blank should have been fixed in the latest version. was approved around 2 days in vrcmg.

Ah! I will have to update and check, I didn’t realize there was an update posted.

> for the second issue I currently have no real way of solving it. It happens if while the animation submenu is open you select another one. If you deselect it first it works fine

Yeah this was the issue, I just have to remember to close the Camera Animations submenu when using it.

Thanks for the cool mod though!
